import { Request, Response } from 'express';
import { sendEmail } from '../services/emailService.js';

export const submitFeedback = async (req: Request, res: Response) => {
    try {
        const { email, message } = req.body;

        if (!email || !message) {
            return res.status(400).json({ error: 'Email and message are required' });
        }

        // Validate email format
        const isEmailValid = email.includes('@') && email.includes('.');
        if (!isEmailValid) {
            return res.status(400).json({ error: 'Please provide a valid email address' });
        }

        const recipient = process.env.FEEDBACK_RECIPIENT_EMAIL || process.env.SMTP_USER;
        if (!recipient) {
            console.error('Feedback configuration error: Neither FEEDBACK_RECIPIENT_EMAIL nor SMTP_USER is set.');
            return res.status(500).json({ error: 'Feedback system is not fully configured.' });
        }

        const subject = `New Customer Feedback from HomeCar`;
        const html = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);">
                <div style="background-color: #065f46; color: white; padding: 15px; border-radius: 8px 8px 0 0; text-align: center;">
                    <h2 style="margin: 0; font-size: 20px;">New Feedback Received</h2>
                </div>
                <div style="padding: 20px;">
                    <p>Hello,</p>
                    <p>You have received new feedback from a user on the HomeCar platform.</p>
                    
                    <div style="margin: 20px 0; border-left: 4px solid #065f46; padding-left: 15px; background-color: #f9fafb; padding-top: 10px; padding-bottom: 10px;">
                        <p style="margin: 0 0 8px 0;"><strong>Sender Email:</strong> <a href="mailto:${email}" style="color: #065f46; text-decoration: none;">${email}</a></p>
                        <p style="margin: 0;"><strong>Message:</strong></p>
                        <p style="margin: 8px 0 0 0; white-space: pre-wrap; font-style: italic; color: #374151;">"${message}"</p>
                    </div>
                    
                    <p style="font-size: 13px; color: #6b7280; margin-top: 30px; border-top: 1px solid #eee; padding-top: 15px;">
                        This message was automatically generated by the HomeCar contact system.
                    </p>
                </div>
            </div>
        `;

        await sendEmail(recipient, subject, html);

        res.json({ success: true, message: 'Feedback sent successfully' });
    } catch (error: any) {
        console.error('Error submitting feedback:', error);
        res.status(500).json({ error: 'Failed to send feedback. Please try again later.' });
    }
};
